const globals = {
  document: 'readonly',
  window: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  requestAnimationFrame: 'readonly',
  performance: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  Blob: 'readonly',
  URL: 'readonly',
  FileReader: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  Uint8Array: 'readonly',
  ArrayBuffer: 'readonly',
  DataView: 'readonly',
  Image: 'readonly',
  HTMLCanvasElement: 'readonly',
  CanvasRenderingContext2D: 'readonly',
  CustomEvent: 'readonly',
  module: 'readonly',
  exports: 'readonly',
  DEEPIRI_DEFAULTS: 'readonly',
  Utils: 'readonly',
  InteractiveEngine: 'readonly',
  InteractiveEncoder: 'readonly',
  InteractivePlayer: 'readonly',
  WallpaperBundler: 'readonly',
};

module.exports = [
  {
    ignores: ['node_modules/**', 'dist/**', 'build/**', '*.min.js', '*.min.css'],
  },
  {
    files: ['src/**/*.js', 'tools/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals,
    },
    rules: {
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      eqeqeq: ['error', 'always'],
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-else-return': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-return': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
      'prefer-promise-reject-errors': 'error',
      'radix': 'error',
    },
  },
  {
    files: ['src/**/*.test.js', 'src/**/*.spec.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        ...globals,
        require: 'readonly',
        global: 'readonly',
        Buffer: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': 'off',
    },
  },
];
